name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    name: Deploy website
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout website code
      uses: actions/checkout@v2

    # Why? In order to avoid bundler version mismatch (happend to me).
    - name: Remove Gemfile.lock
      run: rm -rf Gemfile.lock

    - name: Build website
      uses: jerryjvl/jekyll-build-action@v1

    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
